import { Analytics } from '@vercel/analytics/next'
import type { Metadata } from 'next'
import { Sora } from 'next/font/google'
import './globals.css'

const sora = Sora({
    variable: '--font-sora',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Artist Factory',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html className="overflow-x-hidden scroll-smooth">
            <body className={`${sora.variable} font-main antialiased text-foreground`}>
                {children}
                <Analytics />
            </body>
        </html>
    )
}
