import { routing } from '@/i18n/routing'
import type { Metadata } from 'next'
import { hasLocale, NextIntlClientProvider } from 'next-intl'
import { notFound } from 'next/navigation'
import './globals.css'

import { Analytics } from '@vercel/analytics/next'
import { Sora } from 'next/font/google'
import { Toaster } from 'sonner'
import Providers from './providers'

const sora = Sora({
    variable: '--font-sora',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Artist Factory',
    description: 'Generated by create next app',
}

export default async function LocaleLayout({
    children,
    params,
}: {
    children: React.ReactNode
    params: Promise<{ locale: string }>
}) {
    // Ensure that the incoming `locale` is valid
    const { locale } = await params
    if (!hasLocale(routing.locales, locale)) {
        notFound()
    }

    return (
        <html className="overflow-x-hidden scroll-smooth" lang={locale}>
            <body
                className={`${sora.variable} font-main antialiased text-foreground bg-gradient-main`}
            >
                <NextIntlClientProvider locale={locale}>
                    <Providers>{children}</Providers>
                    <Toaster position="top-center" richColors closeButton />
                    <Analytics />
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
