import { routing } from '@/i18n/routing'
import type { Metadata } from 'next'
import { NextIntlClientProvider, hasLocale } from 'next-intl'
import { notFound } from 'next/navigation'
import './globals.css'

import Footer from '@/components/common/footer'
import Header from '@/components/common/header'
import { Analytics } from '@vercel/analytics/next'
import { Sora } from 'next/font/google'
import { Toaster } from 'sonner'

const sora = Sora({
    variable: '--font-sora',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Artist Factory',
    description: 'Generated by create next app',
}

export default async function LocaleLayout({
    children,
    params,
}: {
    children: React.ReactNode
    params: Promise<{ locale: string }>
}) {
    // Ensure that the incoming `locale` is valid
    const { locale } = await params
    if (!hasLocale(routing.locales, locale)) {
        notFound()
    }

    return (
        <html className="overflow-x-hidden scroll-smooth" lang={'hu'}>
            <body
                className={`${sora.variable} font-main antialiased text-foreground bg-background`}
            >
                <NextIntlClientProvider>
                    <div className="min-h-dvh flex flex-col isolate">
                        <Header />

                        <main className="flex-1">
                            <div className="container mx-auto max-w-6xl px-6 lg:px-8 py-10">
                                {children}
                            </div>
                        </main>

                        <Toaster position="top-center" richColors closeButton />
                        <Footer />
                        <Analytics />
                    </div>
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
