import { AuthDialogProvider } from '@/context/AuthDialogProvider'
import { routing } from '@/i18n/routing'
import { ClerkProvider } from '@clerk/nextjs'
import { Analytics } from '@vercel/analytics/next'
import type { Metadata } from 'next'
import { NextIntlClientProvider, hasLocale } from 'next-intl'
import { Sora } from 'next/font/google'
import { notFound } from 'next/navigation'
import { Toaster } from 'sonner'
import './globals.css'
import React from 'react'

const sora = Sora({
    variable: '--font-sora',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Artist Factory',
    description: 'Generated by create next app',
}

export default async function LocaleLayout({
    children,
    modal,
    params,
}: {
    children: React.ReactNode
    modal: React.ReactNode
    params: Promise<{ locale: string }>
}) {
    const { locale } = await params
    if (!hasLocale(routing.locales, locale)) {
        notFound()
    }

    return (
        <ClerkProvider>
            <AuthDialogProvider>
                <NextIntlClientProvider>
                    <html lang={locale} className="overflow-x-hidden scroll-smooth">
                        <body
                            className={`${sora.variable} font-main antialiased text-foreground bg-background`}
                        >
                            <Toaster position="top-center" richColors closeButton />
                            <Analytics />
                            {children}
                            {modal}
                        </body>
                    </html>
                </NextIntlClientProvider>
            </AuthDialogProvider>
        </ClerkProvider>
    )
}
